### ISSUE TITLE
Unable to resume activity

### ISSUE THREAD

**Issue by narayansikarwar** [bradleygore/nativescript-textinputlayout#1]
![screenshot_2016-05-13-11-45-12 1](https://cloud.githubusercontent.com/assets/19340500/15239461/5d1157e8-1900-11e6-97a9-e072193bc478.png)

**Comment by bradleygore** [comment]
@narayansikarwar What version of the plugin, what does your markup look like, and is there a specific scenario at which this occurs?  I'm going to need a bit more to go on than just the stack trace, please.

**Comment by narayansikarwar** [comment]
plugin version - 0.1.2, when we minimize app after that resume the app then this error is occurred. 
I use your example markup.

**Comment by bradleygore** [comment]
@narayansikarwar thanks - I'll look into this.

**Comment by bradleygore** [comment]
@narayansikarwar Sorry for this issue - I must not have tested that scenario.  I've pushed a fix in v0.1.3 [this commit](https://github.com/bradleygore/nativescript-textinputlayout/commit/1363aa037a5d7f21500c6206ba73cffcb313cdde)

remove/readd the plugin and you should be good to go
`tns plugin remove nativescript-textinputlayout`
`tns plugin add nativescript-textinputlayout`

**Comment by narayansikarwar** [comment]
@bradleygore thanks for resolve this issue. I'll tested this its working fine.
