### ISSUE TITLE
On iOS, I get a series of syntax errors during compile, leading to the app being unable to install on the emulator. Works OK on Windows emulating Android.

### ISSUE THREAD

**Issue by nmandyam** [bradleygore/nativescript-textinputlayout#10]
I recently adding the TIL plugin to my app and it's all OK on the Windows machine I use to develop the Android version. But when I take the same code to iOS, I get all kinds of errors, finally failing to deploy the code on the emulator. I removed the platform, reinstalled it, made no difference.

Here's the command that starts of the errors and beginning of the errors:

> CompileSwift normal x86_64 /Users/rk/Desktop/clg/platforms/ios/Pods/SkyFloatingLabelTextField/Sources/SkyFloatingLabelTextField.swift
>     cd /Users/rk/Desktop/clg/platforms/ios/Pods
>     /Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/swift -frontend -c -primary-file /Users/rk/Desktop/clg/platforms/ios/Pods/SkyFloatingLabelTextField/Sources/SkyFloatingLabelTextField.swift /Users/rk/Desktop/clg/platforms/ios/Pods/SkyFloatingLabelTextField/Sources/SkyFloatingLabelTextFieldWithIcon.swift /Users/rk/Desktop/clg/platforms/ios/Pods/SkyFloatingLabelTextField/Sources/UITextField+fixCaretPosition.swift -target x86_64-apple-ios8.0 -enable-objc-interop -sdk /Applications/Xcode.app/Contents/Developer/Platforms/iPhoneSimulator.platform/Developer/SDKs/iPhoneSimulator9.3.sdk -I /Users/rk/Desktop/clg/platforms/ios/build/emulator -F /Users/rk/Desktop/clg/platforms/ios/build/emulator -enable-testing -g -import-underlying-module -module-cache-path /Users/rk/Library/Developer/Xcode/DerivedData/ModuleCache -D COCOAPODS -serialize-debugging-options -Xcc -I/Users/rk/Library/Developer/Xcode/DerivedData/clg-esiqesllznbtflbhjuwlylgzrrun/Build/Intermediates/Pods.build/Debug-iphonesimulator/SkyFloatingLabelTextField.build/swift-overrides.hmap -Xcc -iquote -Xcc /Users/rk/Library/Developer/Xcode/DerivedData/clg-esiqesllznbtflbhjuwlylgzrrun/Build/Intermediates/Pods.build/Debug-iphonesimulator/SkyFloatingLabelTextField.build/SkyFloatingLabelTextField-generated-files.hmap -Xcc -I/Users/rk/Library/Developer/Xcode/DerivedData/clg-esiqesllznbtflbhjuwlylgzrrun/Build/Intermediates/Pods.build/Debug-iphonesimulator/SkyFloatingLabelTextField.build/SkyFloatingLabelTextField-own-target-headers.hmap -Xcc -I/Users/rk/Library/Developer/Xcode/DerivedData/clg-esiqesllznbtflbhjuwlylgzrrun/Build/Intermediates/Pods.build/Debug-iphonesimulator/SkyFloatingLabelTextField.build/SkyFloatingLabelTextField-all-non-framework-target-headers.hmap -Xcc -ivfsoverlay -Xcc /Users/rk/Library/Developer/Xcode/DerivedData/clg-esiqesllznbtflbhjuwlylgzrrun/Build/Intermediates/Pods.build/all-product-headers.yaml -Xcc -iquote -Xcc /Users/rk/Library/Developer/Xcode/DerivedData/clg-esiqesllznbtflbhjuwlylgzrrun/Build/Intermediates/Pods.build/Debug-iphonesimulator/SkyFloatingLabelTextField.build/SkyFloatingLabelTextField-project-headers.hmap -Xcc -I/Users/rk/Desktop/clg/platforms/ios/build/emulator/include -Xcc -I/Users/rk/Desktop/clg/platforms/ios/Pods/Headers/Private -Xcc -I/Users/rk/Desktop/clg/platforms/ios/Pods/Headers/Public -Xcc -I/Users/rk/Library/Developer/Xcode/DerivedData/clg-esiqesllznbtflbhjuwlylgzrrun/Build/Intermediates/Pods.build/Debug-iphonesimulator/SkyFloatingLabelTextField.build/DerivedSources/x86_64 -Xcc -I/Users/rk/Library/Developer/Xcode/DerivedData/clg-esiqesllznbtflbhjuwlylgzrrun/Build/Intermediates/Pods.build/Debug-iphonesimulator/SkyFloatingLabelTextField.build/DerivedSources -Xcc -DPOD_CONFIGURATION_DEBUG=1 -Xcc -DDEBUG=1 -Xcc -DCOCOAPODS=1 -Xcc -ivfsoverlay -Xcc /Users/rk/Library/Developer/Xcode/DerivedData/clg-esiqesllznbtflbhjuwlylgzrrun/Build/Intermediates/Pods.build/Debug-iphonesimulator/SkyFloatingLabelTextField.build/unextended-module-overlay.yaml -Xcc -working-directory/Users/rk/Desktop/clg/platforms/ios/Pods -emit-module-doc-path /Users/rk/Library/Developer/Xcode/DerivedData/clg-esiqesllznbtflbhjuwlylgzrrun/Build/Intermediates/Pods.build/Debug-iphonesimulator/SkyFloatingLabelTextField.build/Objects-normal/x86_64/SkyFloatingLabelTextField~partial.swiftdoc -Onone -module-name SkyFloatingLabelTextField -emit-module-path /Users/rk/Library/Developer/Xcode/DerivedData/clg-esiqesllznbtflbhjuwlylgzrrun/Build/Intermediates/Pods.build/Debug-iphonesimulator/SkyFloatingLabelTextField.build/Objects-normal/x86_64/SkyFloatingLabelTextField~partial.swiftmodule -serialize-diagnostics-path /Users/rk/Library/Developer/Xcode/DerivedData/clg-esiqesllznbtflbhjuwlylgzrrun/Build/Intermediates/Pods.build/Debug-iphonesimulator/SkyFloatingLabelTextField.build/Objects-normal/x86_64/SkyFloatingLabelTextField.dia -emit-dependencies-path /Users/rk/Library/Developer/Xcode/DerivedData/clg-esiqesllznbtflbhjuwlylgzrrun/Build/Intermediates/Pods.build/Debug-iphonesimulator/SkyFloatingLabelTextField.build/Objects-normal/x86_64/SkyFloatingLabelTextField.d -emit-reference-dependencies-path /Users/rk/Library/Developer/Xcode/DerivedData/clg-esiqesllznbtflbhjuwlylgzrrun/Build/Intermediates/Pods.build/Debug-iphonesimulator/SkyFloatingLabelTextField.build/Objects-normal/x86_64/SkyFloatingLabelTextField.swiftdeps -o /Users/rk/Library/Developer/Xcode/DerivedData/clg-esiqesllznbtflbhjuwlylgzrrun/Build/Intermediates/Pods.build/Debug-iphonesimulator/SkyFloatingLabelTextField.build/Objects-normal/x86_64/SkyFloatingLabelTextField.o
> /Users/rk/Desktop/clg/platforms/ios/Pods/SkyFloatingLabelTextField/Sources/SkyFloatingLabelTextField.swift:15:1: error: expected declaration
> open class SkyFloatingLabelTextField: UITextField {
> ^
> /Users/rk/Desktop/clg/platforms/ios/Pods/SkyFloatingLabelTextField/Sources/SkyFloatingLabelTextField.swift:23:5: error: expected declaration
>     fileprivate func updateTextAligment() {
>

There are a WHOLE LOT of other such syntax errors - errors about declarations not being separated by a ';', expected declarations not found and so on.
Any ideas on how I can fix this?

**Comment by bradleygore** [comment]
@nmandyam This is the first I've seen of this issue, but it looks like something with the pod itself vs the plugin based on the swift compiler error output. I'm honestly not sure - and I've not been doing any NativeScript (or mobile) dev for quite a while so I'm pretty out of the loop right now. May want to reach out to the NativeScript Slack channel.

**Comment by bradleygore** [comment]
Hey @nmandyam - another user had issues and updating the pod version helped them. I'll try to get the pod version updated in the source soon. See #11 for their solution and see if that helps.

**Comment by bradleygore** [comment]
@nmandyam - did that other solution to update the pod version help? I've also just released [v2.0.2](https://github.com/bradleygore/nativescript-textinputlayout/commit/6013350a008202b4769f5347c4e79933c5b53e85) that has some great updates and the updated README contains more info around the pod and version needed.
