### ISSUE TITLE
iOS build with Xcode 8 throws "Command xcodebuild failed with exit code 65"

### ISSUE THREAD

**Issue by rhanb** [bradleygore/nativescript-textinputlayout#11]
Using the plugin to build a project with Xcode 8 is throwing due to:

=== BUILD TARGET MaterialCard OF PROJECT Pods WITH CONFIGURATION Debug === 
```
“Use Legacy Swift Language Version” (SWIFT_VERSION) is required 
to be configured correctly for targets which use Swift. 
Use the [Edit > Convert > To Current Swift Syntax…] menu to choose a Swift
version or use the Build Settings editor to configure the build setting directly. 
```

Fixed the issue by changing the Podfile:

```
pod 'SkyFloatingLabelTextField', '~> 3.2.0'

post_install do |installer|
    installer.pods_project.targets.each do |target|
      target.build_configurations.each do |config|
        config.build_settings['SWIFT_VERSION'] = '3.0'
      end
    end
  end
```

Please consider update the pod version, a lots of issue fixed on the iOS part with the latest version.

**Comment by bradleygore** [comment]
@rhanb - I've just released [v2.0.2](https://github.com/bradleygore/nativescript-textinputlayout/commit/6013350a008202b4769f5347c4e79933c5b53e85) that has bug fixes as well as pulls in updated `SkyFloatingLabelTextField` 3.3.0 and updated README documentation. You should be good to go 😄
