### ISSUE TITLE
nativescript-textinputlayout selectedTitleColor is not working in ios

### ISSUE THREAD

**Issue by priyangamani** [bradleygore/nativescript-textinputlayout#12]
<TIL:TextInputLayout
    hint="Email"
    color="#000000"
    tintColor="#d745ff"
    lineColor="#d745ff"
    selectedTitleColor="#ff45ca"
    selectedLineColor="#7a45ff"
    lineHeight="1.25"
    selectedLineHeight="3.5" />

**Comment by priyangamani** [comment]
I dont see anything in your code that should mess up the textfield properties like secure, but its not working with these text fields.

**Comment by bradleygore** [comment]
@priyangamani - is this still an issue? I've just released [v2.0.2](https://github.com/bradleygore/nativescript-textinputlayout/commit/6013350a008202b4769f5347c4e79933c5b53e85) and `selectedTitleColor` appears to be working well. Also, that update fixes the issue where normal `TextField` props weren't working 😄
