### ISSUE TITLE
Add Compatilibity with Xcode 9

### ISSUE THREAD

**Issue by giordanocardillo** [bradleygore/nativescript-textinputlayout#13]
This plugin is not compatible with xcode 9, I think it needs to update the  `SkyFloatingLabelTextField` version used

**Comment by giordanocardillo** [comment]
After some research, the problem isn't from this, It's something related to `SkyFloatingLabelTextField`, CLOSING.

**Comment by giordanocardillo** [comment]
For everyone having issues with `SkyFloatingLabelTextField` with Xcode 9

1. Run `tns build ios`, you will get a fail saying that `SWIFT_VERSION` is not defined
2. Open up `platforms/ios/Pods/Pods.xcodeproj/project.pbxproj` file
3. Search this file for `SkyFloatingLabelTextField`
4. In this configuration, after `VERSION_INFO_PREFIX = "";` put `SWIFT_VERSION = 3.0;`
5. Done

**Comment by souly1** [comment]
Thanks for the solution. While this solution worked, it is not very maintainable (working under platforms folder)
anyone got a solution which  will persist upon platform remove/add ?
