### ISSUE TITLE
Manage formControl

### ISSUE THREAD

**Issue by papangproduction** [bradleygore/nativescript-textinputlayout#14]
Hi,

We try the plugin, all is OK on Android, but in IOS we can't map with FormControl to set validator for the input. Is it possible (with angular version) ?

Ty

**Comment by bradleygore** [comment]
@papangproduction - I don't use Angular with NativeScript, so honestly not sure. I just released [v2.0.2](https://github.com/bradleygore/nativescript-textinputlayout/commit/6013350a008202b4769f5347c4e79933c5b53e85) that fixes some bugs where the `TextField` props weren't working (thus weren't updating model values). Give it a try now and see! 

I'll go ahead and close this in case it takes care of it, feel free to reopen if not - but as I don't use Angular it may not be something I dig into so PRs will be welcome for this 😄
