### ISSUE TITLE
How to use this in Nativescript angular

### ISSUE THREAD

**Issue by akshath4u** [bradleygore/nativescript-textinputlayout#17]

**Comment by bradleygore** [comment]
@akshath4u - I don't use angular w/ NativeScript, nor do I do anything especially to support or prevent using this plugin with Angular.

**Comment by bradmartin** [comment]
It works similar to all UI plugins, https://docs.nativescript.org/plugins/angular-third-party#simple-elements: registerElement then drop the tag in your markup 👍 just have to remember angular templates require closing tag and can't self-close.

**Comment by bradleygore** [comment]
Thanks @bradmartin - I wasn't aware of that, but will refer to it next time!

**Comment by souly1** [comment]
For quick reference:
`registerElement("TextInputLayout", () => require("nativescript-textinputlayout").TextInputLayout);
`
