### ISSUE TITLE
How to use in Nativescript Angular iOS?

### ISSUE THREAD

**Issue by isaacfi** [bradleygore/nativescript-textinputlayout#18]
Hi,

Do you have an example with [(ngModel)] iOS aproach?

This is because in the use with iOS there is no an explicit TextField tag.

Regards.

**Comment by bradleygore** [comment]
@isaacfi - I don't use NS w/ Angular, so not sure. However, in the documentation for this plugin it does not show using `TextField` with iOS - that's only for Android. Please check out the iOS specific section of the docs - it is essentially just a bridge to the SkyFloatingLabelTextField pod.

Similar question was asked in issue #17 - please check out the NS documentation referenced there.

**Comment by isaacfi** [comment]
Ok, I can to make work in iOS as view as #17 said but, I believe that ngModel support is needed. However, I will try a workaround.

**Comment by isaacfi** [comment]
Do you have the data binding example to the xml/typescript version for iOS?

Thanx

**Comment by bradleygore** [comment]
@isaacfi - both the demo app and the docs in the readme show the app in use w/ data binding using xml+typescript. So, I'm not sure what exactly you're looking for - are you needing something more specific? Apologies if I misunderstand what it is you need.

**Comment by bradleygore** [comment]
Closing: No Response.
