### ISSUE TITLE
changing hint color

### ISSUE THREAD

**Issue by shabib3** [bradleygore/nativescript-textinputlayout#21]
Hey,

first of all thank you for the plugin it is awesome!

There is a way to change the hint color? (before I tapped the textview)

Thanks!

**Comment by bradleygore** [comment]
Hi @shabib3 - I just merged in a PR that fixes this. Please pull in `v2.0.3` and see if that takes care of the issue for you 😃

**Comment by shabib3** [comment]
Hi @bradleygore - Thanks!
I saw that you added the `tintColor` property, but it seem to be available only IOS...How can I do it on Android?

**Comment by venkateshsj** [comment]
This is a great plugin! As always the expectation for flexibility is always more. :wink:

In case of floating labels on  web I display hint text with a red color asterisk to denote compulsory/mandatory fields. For e.g.,
**Enter your Name** * => here I want 'Enter your Name' in dark blue and the '*' in red color. Can I achieve something similar in your plugin?
