### ISSUE TITLE
secure="true" ignored on TextField

### ISSUE THREAD

**Issue by benjaminhorner** [bradleygore/nativescript-textinputlayout#23]
Secure input is ignored.

  ```
        <TextInputLayout 
            class="form-input"
            hint="{{ user.passwordHint }}"
            hintAnimationEnabled="true"
            hintTextAppearance="SpecialTextInputLayout"
            [tintColor]="textInputLayout.tintColor"
            [lineColor]="textInputLayout.lineColor"
            [selectedTitleColor]="textInputLayout.selectedTitleColor"
            [selectedLineColor]="textInputLayout.selectedLineColor">
              <TextField 
                #passwordTextField
                id="passwordTextField"
                [editable]="!isLoading"
                [(ngModel)]="user.password" 
                autocorrect="false" 
                autocapitalizationType="none"
                secure="true"
                returnKeyType="done"
                returnPress="submit()">
              </TextField>
          </TextInputLayout>
```

The secure="true" does not work with textinputlayout added.

**Comment by chuckmitchell** [comment]
I also have this issue on iOS 11.0.3
Works fine on android.

**Comment by chuckmitchell** [comment]
The issue here might be that you are not using a single TextInputLayout tag for iOS as described in the instructions.

**Comment by benjaminhorner** [comment]
@chuckmitchell I tried making it the bare minimum on iOS:
a single TextInputLayout tag and a single secure TextView… and it does not resolve the issue. Moreover, If I do a single TextInputLayout tag, I cannot set the hint for each TextView individually anymore. I am not sure te documentation says you should use a single tag for iOS. I think it just means a single child tag.

**Comment by bradleygore** [comment]
There should **NOT** be a nested `TextField` with iOS. The docs are very explicit about that:

https://github.com/bradleygore/nativescript-textinputlayout#ios

```
<TIL:TextInputLayout
    hint="{{ hint }}"
    isEnabled="{{ isEnabled }}"
    disabledColor="#c3c3c3"
    error="{{ error }}"
    text="{{ demoText }}"
    title="{{ title }}"
    color="{{ error ? '#aa0000' : '#d745ff' }}"
    tintColor="#d745ff"
    lineColor="#d745ff"
    selectedTitleColor="#ff45ca"
    selectedLineColor="#7a45ff"
    lineHeight="1.25"
    selectedLineHeight="3.5" />
```

**Comment by bradleygore** [comment]
@benjaminhorner - also, you can set the `hint` for each `TextInputLayout` individually (providing your variables backing the value are individualized...) as they are individual instances and in no way relating to one another... Please review the demo - there are multiple fields all with different hints in the demo app.

**Comment by benjaminhorner** [comment]
@bradleygore : thanks for your response. My bad. 
However, the `secure="true"` still does not work on iOS. Here is the layout I am using. 

            
            <TextInputLayout 
                #usernameTextField
                id="usernameTextField"
                class="form-input form-textfield"
                [hint]="user.usernameHint"
                hintAnimationEnabled="true"
                hintTextAppearance="SpecialTextInputLayout"
                [tintColor]="textInputLayout.tintColor"
                [lineColor]="textInputLayout.lineColor"
                [selectedTitleColor]="textInputLayout.selectedTitleColor"
                [selectedLineColor]="textInputLayout.selectedLineColor"
                [editable]="!isLoading"
                [(ngModel)]="user.username" 
                autocorrect="false" 
                autocapitalizationType="none"
                returnKeyType="next" 
                returnPress="focusSecond">
            </TextInputLayout>
            
            
            <TextInputLayout 
                #instanceTextField
                id="instanceTextField"
                class="form-input"
                hint="{{ user.instanceNameHint }}"
                hintAnimationEnabled="true"
                hintTextAppearance="SpecialTextInputLayout"
                [tintColor]="textInputLayout.tintColor"
                [lineColor]="textInputLayout.lineColor"
                [selectedTitleColor]="textInputLayout.selectedTitleColor"
                [selectedLineColor]="textInputLayout.selectedLineColor"
                [editable]="!isLoading"
                [(ngModel)]="user.instanceName" 
                autocorrect="false" 
                autocapitalizationType="none" 
                returnKeyType="next" 
                returnPress="focusThird">
            </TextInputLayout>
            
            
            <TextInputLayout 
                #passwordTextField
                id="passwordTextField"
                class="form-input"
                hint="{{ user.passwordHint }}"
                hintAnimationEnabled="true"
                hintTextAppearance="SpecialTextInputLayout"
                [tintColor]="textInputLayout.tintColor"
                [lineColor]="textInputLayout.lineColor"
                [selectedTitleColor]="textInputLayout.selectedTitleColor"
                [selectedLineColor]="textInputLayout.selectedLineColor"
                [editable]="!isLoading"
                [(ngModel)]="user.password" 
                autocorrect="false" 
                autocapitalizationType="none"
                secure="true"
                returnKeyType="done"
                returnPress="submit()">
            </TextInputLayout>

I suppose in a way this is related to my other question [here](https://github.com/bradleygore/nativescript-textinputlayout/issues/24). For exampl if I wanted to add padding to the `TextView` (or on iOS on the `TextInputLayout`).

**Comment by bradleygore** [comment]
Styling issue is separate, so I'll only address secure here: The ios version of this simply inherits from the nativescript `TextField` (see [here](https://github.com/bradleygore/nativescript-textinputlayout/blob/master/textInputLayout.ios.ts#L118)). If the `TextField` supports `secure` on iOS, then great - this should too just as it supports the `text` property. I am not sure why it would not support it exactly the same.

**Comment by bradleygore** [comment]
@benjaminhorner - was this closed because it ended up working, or some other reason?

**Comment by benjaminhorner** [comment]
@bradleygore yes it works. So does the styling… partially. Padding does not work.
