### ISSUE TITLE
keyboardType not working on ios

### ISSUE THREAD

**Issue by giorgi-abashidze** [bradleygore/nativescript-textinputlayout#25]
keyboardType not working on ios device....

```
<TIL:TextInputLayout android:height="60" ios:height="45" hint="Amount" 
                                class="halfTxtField inplay pull-left m-t-15"
                                ios:class="halfTxtField pull-left" 
                                hintTextAppearance="SpecialTextInputLayout"
                              
                                text="{{amount}}" >
                                    <TextView text="{{amount}}" keyboardType="number" />
 </TIL:TextInputLayout>
```

**Comment by bradleygore** [comment]
Please read the documentation - you do not nest a `TextView` inside `TextInputLayout` on IOS...

**Comment by giorgi-abashidze** [comment]
if not textview where can i put keyboardType? like this? : <TIL:TextInputLayout keyboardType="number"> ?

**Comment by bradleygore** [comment]
Yes - for iOS the documentation states:

> So, instead of a TextInpuLayout that wraps a TextField, we just need a single element and we get to take advantage of all the normal TextField bindings that comes from NativeScript!

And the code examples are very clear:

```
<TIL:TextInputLayout
    hint="{{ hint }}"
    isEnabled="{{ isEnabled }}"
    disabledColor="#c3c3c3"
    error="{{ error }}"
    text="{{ demoText }}"
    title="{{ title }}"
    color="{{ error ? '#aa0000' : '#d745ff' }}"
    tintColor="#d745ff"
    lineColor="#d745ff"
    selectedTitleColor="#ff45ca"
    selectedLineColor="#7a45ff"
    lineHeight="1.25"
    selectedLineHeight="3.5" />
```

Again, please read the documentation for most complete information: https://github.com/bradleygore/nativescript-textinputlayout#ios
