### ISSUE TITLE
Support for Nativescript 4.x.x

### ISSUE THREAD

**Issue by shyamseshadri** [bradleygore/nativescript-textinputlayout#27]
Considering that Nativescript 4.x.x is out, this plugin should support it.

I believe there are no breaking changes, but the [following line](https://github.com/bradleygore/nativescript-textinputlayout/blob/master/package.json#L48) prevents a bump up in the version.

Would appreciate if you could take a look and bump it up

**Comment by bradleygore** [comment]
Resolved with 1fd49b95b5fa420ec88df44e31cd9ef681402791 and published as version 2.0.4
