### ISSUE TITLE
iOS Angular binding

### ISSUE THREAD

**Issue by edusperoni** [bradleygore/nativescript-textinputlayout#28]
Hello,

I've tried using this plugin on iOS and did not have success with the two-way binding using ngModel.

Example:

```
<android>
        <TextInputLayout hint="Login" hintAnimationEnabled="true">
            <TextField [isEnabled]="!loggingIn" [(ngModel)]="user.login" keyboardType="number" returnKeyType="next" maxLength="11"></TextField>
        </TextInputLayout>
        <TextInputLayout hint="Password" hintAnimationEnabled="true">
            <TextField [isEnabled]="!loggingIn" [(ngModel)]="user.password" returnKeyType="next" (returnPress)="submit()" secure="true"></TextField>
        </TextInputLayout>
    </android>
    <ios>
        <TextInputLayout hint="Login" hintAnimationEnabled="true" [isEnabled]="!loggingIn" [(ngModel)]="user.login" keyboardType="number"
            returnKeyType="next" maxLength="11" ngDefaultControl></TextInputLayout>
        <TextInputLayout hint="Password" hintAnimationEnabled="true" [isEnabled]="!loggingIn" [(ngModel)]="user.password" returnKeyType="next"
            (returnPress)="submit()" secure="true" ngDefaultControl></TextInputLayout>
    </ios>
```

Although the input works fine, the iOS version does not update the user.login and user.password values. Is there any way to make the angular binding work on the iOS version?

**Comment by bradleygore** [comment]
I don't use angular w/ NativeScript, so not sure. PRs welcome.

**Comment by ExaltedJim** [comment]
As a workaround, I was able to get this working on iOS in angular using a combination of [text] and (textChange):

```
<ios>
    <TextInputLayout hint="Login" [text]="user.login" (textChange)="updateModelValue($event)"/>
</ios>
```

```javascript
updateModelValue(args) {
    this.user.login = args.object.text;
}
```
Not as nice as using [(ngModel)], but it at least works for me for the time being.

**Comment by alqabali** [comment]
the same problem here ! any PRs?

**Comment by bradleygore** [comment]
@alqabali - just use `[text]` and `(textChange)` bindings as @ExaltedJim pointed out. There is a PR, however I'm still not sure I want to put angular-specific stuff in this repo - the purpose of this repo is bindings between {N} and the android/iOS components used vs {N}-Angular and the android/iOS components used.
