### ISSUE TITLE
Error using this plugin on android version 4.4.2

### ISSUE THREAD

**Issue by arma7x** [bradleygore/nativescript-textinputlayout#3]
Here my error logs

An uncaught Exception occurred on "main" thread.
java.lang.RuntimeException: Unable to resume activity {org.nativescript.slimNative/com.tns.NativeScriptActivity}: com.tns.NativeScriptException: 
Calling js method onCreateView failed

Error: java.lang.ClassCastException: org.nativescript.widgets.CommonLayoutParams cannot be cast to android.widget.LinearLayout$LayoutParams
    android.support.design.widget.TextInputLayout.updateInputLayoutMargins(TextInputLayout.java:371)
    android.support.design.widget.TextInputLayout.addView(TextInputLayout.java:271)
    android.view.ViewGroup.addView(ViewGroup.java:3509)
    android.view.ViewGroup.addView(ViewGroup.java:3485)
    com.tns.Runtime.callJSMethodNative(Native Method)
    com.tns.Runtime.dispatchCallJSMethodNative(Runtime.java:1022)
    com.tns.Runtime.callJSMethodImpl(Runtime.java:907)
    com.tns.Runtime.callJSMethod(Runtime.java:895)
    com.tns.Runtime.callJSMethod(Runtime.java:879)
    com.tns.Runtime.callJSMethod(Runtime.java:871)
    com.tns.FragmentClass.onCreateView(android.app.Fragment.java)
    android.app.Fragment.performCreateView(Fragment.java:1700)
    android.app.FragmentManagerImpl.moveToState(FragmentManager.java:906)
    android.app.FragmentManagerImpl.moveToState(FragmentManager.java:1078)
    android.app.BackStackRecord.run(BackStackRecord.java:698)
    android.app.FragmentManagerImpl.execPendingActions(FragmentManager.java:1463)
    android.app.Activity.performResume(Activity.java:5495)
    android.app.ActivityThread.performResumeActivity(ActivityThread.java:2980)
    android.app.ActivityThread.handleResumeActivity(ActivityThread.java:3023)
    android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:2425)
    android.app.ActivityThread.access$800(ActivityThread.java:151)
    android.app.ActivityThread$H.handleMessage(ActivityThread.java:1342)
    android.os.Handler.dispatchMessage(Handler.java:110)
    android.os.Looper.loop(Looper.java:193)
    android.app.ActivityThread.main(ActivityThread.java:5324)
    java.lang.reflect.Method.invokeNative(Native Method)
    java.lang.reflect.Method.invoke(Method.java:515)
    com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:829)
    com.android.internal.os.ZygoteInit.main(ZygoteInit.java:645)
    dalvik.system.NativeStart.main(Native Method)
File: "/data/data/org.nativescript.slimNative/files/app/tns_modules/nativescript-textinputlayout/textInputLayout.js, line: 101, column: 29

StackTrace: 
	Frame: function:'onChildLoaded', file:'/data/data/org.nativescript.slimNative/files/app/tns_modules/nativescript-textinputlayout/textInputLayout.js', line: 101, column: 30
	Frame: function:'Observable.notify', file:'/data/data/org.nativescript.slimNative/files/app/tns_modules/data/observable/observable.js', line: 146, column: 32
	Frame: function:'Observable._emit', file:'/data/data/org.nativescript.slimNative/files/app/tns_modules/data/observable/observable.js', line: 168, column: 18
	Frame: function:'View.onLoaded', file:'/data/data/org.nativescript.slimNative/files/app/tns_modules/ui/core/view-common.js', line: 743, column: 14
	Frame: function:'View.onLoaded', file:'/data/data/org.nativescript.slimNative/files/app/tns_modules/ui/core/view.js', line: 83, column: 35
	Frame: function:'eachChild', file:'/data/data/org.nativescript.slimNative/files/app/tns_modules/ui/core/view-common.js', line: 748, column: 23
	Frame: function:'TextInputLayout._eachChildView', file:'/data/data/org.nativescript.slimNative/files/app/tns_modules/nativescript-textinputlayout/textInputLayout.common.js', line: 93, column: 13
	Frame: function:'View._loadEachChildView', file:'/data/data/org.nativescript.slimNative/files/app/tns_modules/ui/core/view-common.js', line: 751, column: 18
	Frame: function:'View.onLoaded', file:'/data/data/org.nativescript.slimNative/files/app/tns_modules/ui/core/view-common.js', line: 741, column: 14
	Frame: function:'View.onLoaded', file:'/data/data/org.nativescript.slimNative/files/app/tns_modules/ui/core/view.js', line: 83, column: 35
	Frame: function:'eachChild', file:'/data/data/org.nativescript.slimNative/files/app/tns_modules/ui/core/view-common.js', line: 748, column: 23
	Frame: function:'LayoutBase._eachChildView', file:'/data/data/org.nativescript.slimNative/files/app/tns_modules/ui/layouts/layout-base-common.js', line: 144, column: 22
	Frame: function:'View._loadEachChildView', file:'/data/data/org.nativescript.slimNative/files/app/tns_modules/ui/core/view-common.js', line: 751, column: 18
	Frame: function:'View.onLoaded', file:'/data/data/org.nativescript.slimNative/files/app/tns_modules/ui/core/view-common.js', line: 741, column: 14
	Frame: function:'View.onLoaded', file:'/data/data/org.nativescript.slimNative/files/app/tns_modules/ui/core/view.js', line: 83, column: 35
	Frame: function:'eachChild', file:'/data/data/org.nativescript.slimNative/files/app/tns_modules/ui/core/view-common.js', line: 748, column: 23
	Frame: function:'LayoutBase._eachChildView', file:'/data/data/org.nativescript.slimNative/files/app/tns_modules/ui/layouts/layout-base-common.js', line: 144, column: 22
	Frame: function:'View._loadEachChildView', file:'/data/data/org.nativescript.slimNative/files/app/tns_modules/ui/core/view-common.js', line: 751, column: 18
	Frame: function:'View.onLoaded', file:'/data/data/org.nativescript.slimNative/files/app/tns_modules/ui/core/view-common.js', line: 741, column: 14
	Frame: function:'View.onLoaded', file:'/data/data/org.nativescript.slimNative/files/app/tns_modules/ui/core/view.js', line: 83, column: 35
	Frame: function:'eachChild', file:'/data/data/org.nativescript.slimNative/files/app/tns_modules/ui/core/view-common.js', line: 748, column: 23
	Frame: function:'ContentView._eachChildView', file:'/data/data/org.nativescript.slimNative/files/app/tns_modules/ui/content-view/content-view.js', line: 65, column: 13
	Frame: function:'View._loadEachChildView', file:'/data/data/org.nativescript.slimNative/files/app/tns_modules/ui/core/view-common.js', line: 751, column: 18
	Frame: function:'View.onLoaded', file:'/data/data/org.nativescript.slimNative/files/app/tns_modules/ui/core/view-common.js', line: 741, column: 14
	Frame: function:'View.onLoaded', file:'/data/data/org.nativescript.slimNative/files/app/tns_modules/ui/core/view.js', line: 83, column: 35
	Frame: function:'ScrollView.onLoaded', file:'/data/data/org.nativescript.slimNative/files/app/tns_modules/ui/scroll-view/scroll-view-common.js', line: 40, column: 35
	Frame: function:'eachChild', file:'/data/data/org.nativescript.slimNative/files/app/tns_modules/ui/core/view-common.js', line: 748, column: 23
	Frame: function:'ContentView._eachChildView', file:'/data/data/org.nativescript.slimNative/files/app/tns_modules/ui/content-view/content-view.js', line: 65, column: 13
	Frame: function:'Page._eachChildView', file:'/data/data/org.nativescript.slimNative/files/app/tns_modules/ui/page/page-common.js', line: 285, column: 41
	Frame: function:'DrawerPage._eachChildView', file:'/data/data/org.nativescript.slimNative/files/app/tns_modules/nativescript-telerik-ui/sidedrawer/drawerpage/drawerpage.js', line: 111, column: 41
	Frame: function:'View._loadEachChildView', file:'/data/data/org.nativescript.slimNative/files/app/tns_modules/ui/core/view-common.js', line: 751, column: 18
	Frame: function:'View.onLoaded', file:'/data/data/org.nativescript.slimNative/files/app/tns_modules/ui/core/view-common.js', line: 741, column: 14
	Frame: function:'View.onLoaded', file:'/data/data/org.nativescript.slimNative/files/app/tns_modules/ui/core/view.js', line: 83, column: 35
	Frame: function:'Page.onLoaded', file:'/data/data/org.nativescript.slimNative/files/app/tns_modules/ui/page/page-common.js', line: 53, column: 35
	Frame: function:'DrawerPage.onLoaded', file:'/data/data/org.nativescript.slimNative/files/app/tns_modules/nativescript-telerik-ui/sidedrawer/drawerpage/drawerpage-common.js', line: 21, column: 35
	Frame: function:'View._addViewCore', file:'/data/data/org.nativescript.slimNative/files/app/tns_modules/ui/core/view-common.js', line: 1173, column: 18
	Frame: function:'View._addViewCore', file:'/data/data/org.nativescript.slimNative/files/app/tns_modules/ui/core/view.js', line: 128, column: 39
	Frame: function:'View._addView', file:'/data/data/org.nativescript.slimNative/files/app/tns_modules/ui/core/view-common.js', line: 1163, column: 14
	Frame: function:'onFragmentShown', file:'/data/data/org.nativescript.slimNative/files/app/tns_modules/ui/frame/frame.js', line: 40, column: 11
	Frame: function:'FragmentCallbacksImplementation.onCreateView', file:'/data/data/org.nativescript.slimNative/files/app/tns_modules/ui/frame/frame.js', line: 612, column: 13
	Frame: function:'FragmentClass.onCreateView', file:'/data/data/org.nativescript.slimNative/files/app/tns_modules/ui/frame/fragment.js', line: 23, column: 38

	at android.app.ActivityThread.performResumeActivity(ActivityThread.java:2994)
	at android.app.ActivityThread.handleResumeActivity(ActivityThread.java:3023)
	at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:2425)
	at android.app.ActivityThread.access$800(ActivityThread.java:151)
	at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1342)
	at android.os.Handler.dispatchMessage(Handler.java:110)
	at android.os.Looper.loop(Looper.java:193)
	at android.app.ActivityThread.main(ActivityThread.java:5324)
	at java.lang.reflect.Method.invokeNative(Native Method)
	at java.lang.reflect.Method.invoke(Method.java:515)
	at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:829)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:645)
	at dalvik.system.NativeStart.main(Native Method)
Caused by: com.tns.NativeScriptException: 
Calling js method onCreateView failed

Error: java.lang.ClassCastException: org.nativescript.widgets.CommonLayoutParams cannot be cast to android.widget.LinearLayout$LayoutParams
    android.support.design.widget.TextInputLayout.updateInputLayoutMargins(TextInputLayout.java:371)
    android.support.design.widget.TextInputLayout.addView(TextInputLayout.java:271)
    android.view.ViewGroup.addView(ViewGroup.java:3509)
    android.view.ViewGroup.addView(ViewGroup.java:3485)
    com.tns.Runtime.callJSMethodNative(Native Method)
    com.tns.Runtime.dispatchCallJSMethodNative(Runtime.java:1022)
    com.tns.Runtime.callJSMethodImpl(Runtime.java:907)
    com.tns.Runtime.callJSMethod(Runtime.java:895)
    com.tns.Runtime.callJSMethod(Runtime.java:879)
    com.tns.Runtime.callJSMethod(Runtime.java:871)
    com.tns.FragmentClass.onCreateView(android.app.Fragment.java)
    android.app.Fragment.performCreateView(Fragment.java:1700)
    android.app.FragmentManagerImpl.moveToState(FragmentManager.java:906)
    android.app.FragmentManagerImpl.moveToState(FragmentManager.java:1078)
    android.app.BackStackRecord.run(BackStackRecord.java:698)
    android.app.FragmentManagerImpl.execPendingActions(FragmentManager.java:1463)
    android.app.Activity.performResume(Activity.java:5495)
    android.app.ActivityThread.performResumeActivity(ActivityThread.java:2980)
    android.app.ActivityThread.handleResumeActivity(ActivityThread.java:3023)
    android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:2425)
    android.app.ActivityThread.access$800(ActivityThread.java:151)
    android.app.ActivityThread$H.handleMessage(ActivityThread.java:1342)
    android.os.Handler.dispatchMessage(Handler.java:110)
    android.os.Looper.loop(Looper.java:193)
    android.app.ActivityThread.main(ActivityThread.java:5324)
    java.lang.reflect.Method.invokeNative(Native Method)
    java.lang.reflect.Method.invoke(Method.java:515)
    com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:829)
    com.android.internal.os.ZygoteInit.main(ZygoteInit.java:645)
    dalvik.system.NativeStart.main(Native Method)
File: "/data/data/org.nativescript.slimNative/files/app/tns_modules/nativescript-textinputlayout/textInputLayout.js, line: 101, column: 29

StackTrace: 
	Frame: function:'onChildLoaded', file:'/data/data/org.nativescript.slimNative/files/app/tns_modules/nativescript-textinputlayout/textInputLayout.js', line: 101, column: 30
	Frame: function:'Observable.notify', file:'/data/data/org.nativescript.slimNative/files/app/tns_modules/data/observable/observable.js', line: 146, column: 32
	Frame: function:'Observable._emit', file:'/data/data/org.nativescript.slimNative/files/app/tns_modules/data/observable/observable.js', line: 168, column: 18
	Frame: function:'View.onLoaded', file:'/data/data/org.nativescript.slimNative/files/app/tns_modules/ui/core/view-common.js', line: 743, column: 14
	Frame: function:'View.onLoaded', file:'/data/data/org.nativescript.slimNative/files/app/tns_modules/ui/core/view.js', line: 83, column: 35
	Frame: function:'eachChild', file:'/data/data/org.nativescript.slimNative/files/app/tns_modules/ui/core/view-common.js', line: 748, column: 23
	Frame: function:'TextInputLayout._eachChildView', file:'/data/data/org.nativescript.slimNative/files/app/tns_modules/nativescript-textinputlayout/textInputLayout.common.js', line: 93, column: 13
	Frame: function:'View._loadEachChildView', file:'/data/data/org.nativescript.slimNative/files/app/tns_modules/ui/core/view-common.js', line: 751, column: 18
	Frame: function:'View.onLoaded', file:'/data/data/org.nativescript.slimNative/files/app/tns_modules/ui/core/view-common.js', line: 741, column: 14
	Frame: function:'View.onLoaded', file:'/data/data/org.nativescript.slimNative/files/app/tns_modules/ui/core/view.js', line: 83, column: 35
	Frame: function:'eachChild', file:'/data/data/org.nativescript.slimNative/files/app/tns_modules/ui/core/view-common.js', line: 748, column: 23
	Frame: function:'LayoutBase._eachChildView', file:'/data/data/org.nativescript.slimNative/files/app/tns_modules/ui/layouts/layout-base-common.js', line: 144, column: 22
	Frame: function:'View._loadEachChildView', file:'/data/data/org.nativescript.slimNative/files/app/tns_modules/ui/core/view-common.js', line: 751, column: 18
	Frame: function:'View.onLoaded', file:'/data/data/org.nativescript.slimNative/files/app/tns_modules/ui/core/view-common.js', line: 741, column: 14
	Frame: function:'View.onLoaded', file:'/data/data/org.nativescript.slimNative/files/app/tns_modules/ui/core/view.js', line: 83, column: 35
	Frame: function:'eachChild', file:'/data/data/org.nativescript.slimNative/files/app/tns_modules/ui/core/view-common.js', line: 748, column: 23
	Frame: function:'LayoutBase._eachChildView', file:'/data/data/org.nativescript.slimNative/files/app/tns_modules/ui/layouts/layout-base-common.js', line: 144, column: 22
	Frame: function:'View._loadEachChildView', file:'/data/data/org.nativescript.slimNative/files/app/tns_modules/ui/core/view-common.js', line: 751, column: 18
	Frame: function:'View.onLoaded', file:'/data/data/org.nativescript.slimNative/files/app/tns_modules/ui/core/view-common.js', line: 741, column: 14
	Frame: function:'View.onLoaded', file:'/data/data/org.nativescript.slimNative/files/app/tns_modules/ui/core/view.js', line: 83, column: 35
	Frame: function:'eachChild', file:'/data/data/org.nativescript.slimNative/files/app/tns_modules/ui/core/view-common.js', line: 748, column: 23
	Frame: function:'ContentView._eachChildView', file:'/data/data/org.nativescript.slimNative/files/app/tns_modules/ui/content-view/content-view.js', line: 65, column: 13
	Frame: function:'View._loadEachChildView', file:'/data/data/org.nativescript.slimNative/files/app/tns_modules/ui/core/view-common.js', line: 751, column: 18
	Frame: function:'View.onLoaded', file:'/data/data/org.nativescript.slimNative/files/app/tns_modules/ui/core/view-common.js', line: 741, column: 14
	Frame: function:'View.onLoaded', file:'/data/data/org.nativescript.slimNative/files/app/tns_modules/ui/core/view.js', line: 83, column: 35
	Frame: function:'ScrollView.onLoaded', file:'/data/data/org.nativescript.slimNative/files/app/tns_modules/ui/scroll-view/scroll-view-common.js', line: 40, column: 35
	Frame: function:'eachChild', file:'/data/data/org.nativescript.slimNative/files/app/tns_modules/ui/core/view-common.js', line: 748, column: 23
	Frame: function:'ContentView._eachChildView', file:'/data/data/org.nativescript.slimNative/files/app/tns_modules/ui/content-view/content-view.js', line: 65, column: 13
	Frame: function:'Page._eachChildView', file:'/data/data/org.nativescript.slimNative/files/app/tns_modules/ui/page/page-common.js', line: 285, column: 41
	Frame: function:'DrawerPage._eachChildView', file:'/data/data/org.nativescript.slimNative/files/app/tns_modules/nativescript-telerik-ui/sidedrawer/drawerpage/drawerpage.js', line: 111, column: 41
	Frame: function:'View._loadEachChildView', file:'/data/data/org.nativescript.slimNative/files/app/tns_modules/ui/core/view-common.js', line: 751, column: 18
	Frame: function:'View.onLoaded', file:'/data/data/org.nativescript.slimNative/files/app/tns_modules/ui/core/view-common.js', line: 741, column: 14
	Frame: function:'View.onLoaded', file:'/data/data/org.nativescript.slimNative/files/app/tns_modules/ui/core/view.js', line: 83, column: 35
	Frame: function:'Page.onLoaded', file:'/data/data/org.nativescript.slimNative/files/app/tns_modules/ui/page/page-common.js', line: 53, column: 35
	Frame: function:'DrawerPage.onLoaded', file:'/data/data/org.nativescript.slimNative/files/app/tns_modules/nativescript-telerik-ui/sidedrawer/drawerpage/drawerpage-common.js', line: 21, column: 35
	Frame: function:'View._addViewCore', file:'/data/data/org.nativescript.slimNative/files/app/tns_modules/ui/core/view-common.js', line: 1173, column: 18
	Frame: function:'View._addViewCore', file:'/data/data/org.nativescript.slimNative/files/app/tns_modules/ui/core/view.js', line: 128, column: 39
	Frame: function:'View._addView', file:'/data/data/org.nativescript.slimNative/files/app/tns_modules/ui/core/view-common.js', line: 1163, column: 14
	Frame: function:'onFragmentShown', file:'/data/data/org.nativescript.slimNative/files/app/tns_modules/ui/frame/frame.js', line: 40, column: 11
	Frame: function:'FragmentCallbacksImplementation.onCreateView', file:'/data/data/org.nativescript.slimNative/files/app/tns_modules/ui/frame/frame.js', line: 612, column: 13
	Frame: function:'FragmentClass.onCreateView', file:'/data/data/org.nativescript.slimNative/files/app/tns_modules/ui/frame/fragment.js', line: 23, column: 38

	at com.tns.Runtime.callJSMethodNative(Native Method)
	at com.tns.Runtime.dispatchCallJSMethodNative(Runtime.java:1022)
	at com.tns.Runtime.callJSMethodImpl(Runtime.java:907)
	at com.tns.Runtime.callJSMethod(Runtime.java:895)
	at com.tns.Runtime.callJSMethod(Runtime.java:879)
	at com.tns.Runtime.callJSMethod(Runtime.java:871)
	at com.tns.FragmentClass.onCreateView(android.app.Fragment.java)
	at android.app.Fragment.performCreateView(Fragment.java:1700)
	at android.app.FragmentManagerImpl.moveToState(FragmentManager.java:906)
	at android.app.FragmentManagerImpl.moveToState(FragmentManager.java:1078)
	at android.app.BackStackRecord.run(BackStackRecord.java:698)
	at android.app.FragmentManagerImpl.execPendingActions(FragmentManager.java:1463)
	at android.app.Activity.performResume(Activity.java:5495)
	at android.app.ActivityThread.performResumeActivity(ActivityThread.java:2980)
	... 12 more
Caused by: java.lang.ClassCastException: org.nativescript.widgets.CommonLayoutParams cannot be cast to android.widget.LinearLayout$LayoutParams
	at android.support.design.widget.TextInputLayout.updateInputLayoutMargins(TextInputLayout.java:371)
	at android.support.design.widget.TextInputLayout.addView(TextInputLayout.java:271)
	at android.view.ViewGroup.addView(ViewGroup.java:3509)
	at android.view.ViewGroup.addView(ViewGroup.java:3485)
	... 26 more

**Comment by arma7x** [comment]
All NativeScript components versions information
┌──────────────────┬─────────────────┬────────────────┬──────────────────┐
│ Component        │ Current version │ Latest version │ Information      │
│ nativescript     │ 2.4.0           │ 2.4.2          │ Update available │
│ tns-core-modules │ 2.4.0           │ 2.4.3          │ Update available │
│ tns-android      │ 2.4.1           │ 2.4.1          │ Up to date       │
│ tns-ios          │                 │ 2.4.0          │ Not installed    │

**Comment by arma7x** [comment]
My xml

<dpg:DrawerPage
  xmlns="http://schemas.nativescript.org/tns.xsd"
  xmlns:dpg="nativescript-telerik-ui/sidedrawer/drawerpage"
  xmlns:drawer="nativescript-telerik-ui/sidedrawer"
  xmlns:widgets="shared/widgets"
  xmlns:statusbar="nativescript-statusbar"
  xmlns:RL="nativescript-ripple"
  xmlns:TIL="nativescript-textinputlayout"
  loaded="loaded">

  <statusbar:StatusBar ios:barStyle="light" />

  <page.actionBar>
    <action-bar title="Slim Native">
      <navigation-button icon="res://ic_menu" tap="toggleDrawer" ios:visibility="collapsed" />
      <action-bar.actionItems>
        <ios>
          <action-item icon="res://ic_menu" ios.position="left" tap="toggleDrawer" />
        </ios>
      </action-bar.actionItems>
    </action-bar>
  </page.actionBar>

  <dpg:DrawerPage.sideDrawer>
  <drawer:rad-side-drawer id="drawer" drawerSize="260">
    <drawer:rad-side-drawer.drawerContent>
      <widgets:drawer-content />
    </drawer:rad-side-drawer.drawerContent>
  </drawer:rad-side-drawer>
  </dpg:DrawerPage.sideDrawer>

<drawer:rad-side-drawer.mainContent>
<ScrollView loaded="mainContentLoaded">
      <stack-layout>
        <image src="~/images/logo.png" id="logo" margin="10" tap="fun" height="100" />
        <label class="h4 grey-text text-darken-4" text="{{ welcomeText }}" margin="10" horizontalAlignment="center" textWrap="true" />
        <stack-layout class="listview" visibility="{{ isLoading == true ? 'collapsed' : 'visible' }}">
        <TIL:TextInputLayout hint="Hint Text">
          <TextField text="" />
        </TIL:TextInputLayout>
        <Repeater items="{{ todoList }}">
          <Repeater.itemTemplate>
            <stack-layout class="listview-inset">
              <RL:Ripple rippleColor="#b2dfdb">
                <Label class="h5 grey-text text-darken-4" text="{{ name }}" horizontalAlignment="center" verticalAlignment="center"/>
              </RL:Ripple>
            </stack-layout>
          </Repeater.itemTemplate>
        </Repeater>
        </stack-layout>
        <ActivityIndicator busy="{{ isLoading }}" rowSpan="2" colSpan="2" />
      </stack-layout>
</ScrollView>
</drawer:rad-side-drawer.mainContent>

</dpg:DrawerPage>

**Comment by arma7x** [comment]
<dpg:DrawerPage
  xmlns="http://schemas.nativescript.org/tns.xsd"
  xmlns:dpg="nativescript-telerik-ui/sidedrawer/drawerpage"
  xmlns:drawer="nativescript-telerik-ui/sidedrawer"
  xmlns:widgets="shared/widgets"
  xmlns:statusbar="nativescript-statusbar"
  xmlns:RL="nativescript-ripple"
  xmlns:TIL="nativescript-textinputlayout"
  loaded="loaded">

  <statusbar:StatusBar ios:barStyle="light" />

  <page.actionBar>
    <action-bar title="Slim Native">
      <navigation-button icon="res://ic_menu" tap="toggleDrawer" ios:visibility="collapsed" />
      <action-bar.actionItems>
        <ios>
          <action-item icon="res://ic_menu" ios.position="left" tap="toggleDrawer" />
        </ios>
      </action-bar.actionItems>
    </action-bar>
  </page.actionBar>

  <dpg:DrawerPage.sideDrawer>
  <drawer:rad-side-drawer id="drawer" drawerSize="260">
    <drawer:rad-side-drawer.drawerContent>
      <widgets:drawer-content />
    </drawer:rad-side-drawer.drawerContent>
  </drawer:rad-side-drawer>
  </dpg:DrawerPage.sideDrawer>

<drawer:rad-side-drawer.mainContent>
<ScrollView loaded="mainContentLoaded">
      <stack-layout>
        <image src="~/images/logo.png" id="logo" margin="10" tap="fun" height="100" />
        <label class="h4 grey-text text-darken-4" text="{{ welcomeText }}" margin="10" horizontalAlignment="center" textWrap="true" />
        <stack-layout class="listview" visibility="{{ isLoading == true ? 'collapsed' : 'visible' }}">
        <TIL:TextInputLayout hint="Hint Text">
          <TextField text="" />
        </TIL:TextInputLayout>
        <Repeater items="{{ todoList }}">
          <Repeater.itemTemplate>
            <stack-layout class="listview-inset">
              <RL:Ripple rippleColor="#b2dfdb">
                <Label class="h5 grey-text text-darken-4" text="{{ name }}" horizontalAlignment="center" verticalAlignment="center"/>
              </RL:Ripple>
            </stack-layout>
          </Repeater.itemTemplate>
        </Repeater>
        </stack-layout>
        <ActivityIndicator busy="{{ isLoading }}" rowSpan="2" colSpan="2" />
      </stack-layout>
</ScrollView>
</drawer:rad-side-drawer.mainContent>

</dpg:DrawerPage>

**Comment by arma7x** [comment]
<dpg:DrawerPage
  xmlns="http://schemas.nativescript.org/tns.xsd"
  xmlns:dpg="nativescript-telerik-ui/sidedrawer/drawerpage"
  xmlns:drawer="nativescript-telerik-ui/sidedrawer"
  xmlns:widgets="shared/widgets"
  xmlns:statusbar="nativescript-statusbar"
  xmlns:RL="nativescript-ripple"
  xmlns:TIL="nativescript-textinputlayout"
  loaded="loaded">

  <statusbar:StatusBar ios:barStyle="light" />

  <page.actionBar>
    <action-bar title="Slim Native">
      <navigation-button icon="res://ic_menu" tap="toggleDrawer" ios:visibility="collapsed" />
      <action-bar.actionItems>
        <ios>
          <action-item icon="res://ic_menu" ios.position="left" tap="toggleDrawer" />
        </ios>
      </action-bar.actionItems>
    </action-bar>
  </page.actionBar>

  <dpg:DrawerPage.sideDrawer>
  <drawer:rad-side-drawer id="drawer" drawerSize="260">
    <drawer:rad-side-drawer.drawerContent>
      <widgets:drawer-content />
    </drawer:rad-side-drawer.drawerContent>
  </drawer:rad-side-drawer>
  </dpg:DrawerPage.sideDrawer>

<drawer:rad-side-drawer.mainContent>
<ScrollView loaded="mainContentLoaded">
      <stack-layout>
        <label class="h4 grey-text text-darken-4" text="{{ welcomeText }}" margin="10" horizontalAlignment="center" textWrap="true" />
        <stack-layout class="listview" visibility="{{ isLoading == true ? 'collapsed' : 'visible' }}">
        <TIL:TextInputLayout hint="Hint Text">
          <TextField text="" />
        </TIL:TextInputLayout>
        <Repeater items="{{ todoList }}">
          <Repeater.itemTemplate>
            <stack-layout class="listview-inset">
              <RL:Ripple rippleColor="#b2dfdb">
                <Label class="h5 grey-text text-darken-4" text="{{ name }}" horizontalAlignment="center" verticalAlignment="center"/>
              </RL:Ripple>
            </stack-layout>
          </Repeater.itemTemplate>
        </Repeater>
        </stack-layout>
        <ActivityIndicator busy="{{ isLoading }}" rowSpan="2" colSpan="2" />
      </stack-layout>
</ScrollView>
</drawer:rad-side-drawer.mainContent>

</dpg:DrawerPage>

**Comment by arma7x** [comment]
`<dpg:DrawerPage
  xmlns="http://schemas.nativescript.org/tns.xsd"
  xmlns:dpg="nativescript-telerik-ui/sidedrawer/drawerpage"
  xmlns:drawer="nativescript-telerik-ui/sidedrawer"
  xmlns:widgets="shared/widgets"
  xmlns:statusbar="nativescript-statusbar"
  xmlns:RL="nativescript-ripple"
  xmlns:TIL="nativescript-textinputlayout"
  loaded="loaded">

  <statusbar:StatusBar ios:barStyle="light" />

  <page.actionBar>
    <action-bar title="Slim Native">
      <navigation-button icon="res://ic_menu" tap="toggleDrawer" ios:visibility="collapsed" />
      <action-bar.actionItems>
        <ios>
          <action-item icon="res://ic_menu" ios.position="left" tap="toggleDrawer" />
        </ios>
      </action-bar.actionItems>
    </action-bar>
  </page.actionBar>

  <dpg:DrawerPage.sideDrawer>
  <drawer:rad-side-drawer id="drawer" drawerSize="260">
    <drawer:rad-side-drawer.drawerContent>
      <widgets:drawer-content />
    </drawer:rad-side-drawer.drawerContent>
  </drawer:rad-side-drawer>
  </dpg:DrawerPage.sideDrawer>

<drawer:rad-side-drawer.mainContent>
<ScrollView loaded="mainContentLoaded">
      <stack-layout>
        <image src="~/images/logo.png" id="logo" margin="10" tap="fun" height="100" />
        <label class="h4 grey-text text-darken-4" text="{{ welcomeText }}" margin="10" horizontalAlignment="center" textWrap="true" />
        <stack-layout class="listview" visibility="{{ isLoading == true ? 'collapsed' : 'visible' }}">
        <TIL:TextInputLayout hint="Hint Text">
          <TextField text="" />
        </TIL:TextInputLayout>
        <Repeater items="{{ todoList }}">
          <Repeater.itemTemplate>
            <stack-layout class="listview-inset">
              <RL:Ripple rippleColor="#b2dfdb">
                <Label class="h5 grey-text text-darken-4" text="{{ name }}" horizontalAlignment="center" verticalAlignment="center"/>
              </RL:Ripple>
            </stack-layout>
          </Repeater.itemTemplate>
        </Repeater>
        </stack-layout>
        <ActivityIndicator busy="{{ isLoading }}" rowSpan="2" colSpan="2" />
      </stack-layout>
</ScrollView>
</drawer:rad-side-drawer.mainContent>

</dpg:DrawerPage>
`

**Comment by bradleygore** [comment]
Hi @arma7x - thanks for reaching out! However, I'm no longer working on NativeScript projects (although I hope to get back to it sometime in 2017), so I've not tested TIL since v2.0 of NativeScript. So, I won't be able to really dig into this for a while.

One thing I'd suggest off the top of my head is to do a view without all those different controls and try TIL alone. If it breaks there, then it's the TIL that's the problem and the stacktrace may be more helpful. Otherwise, if it doesn't break there, then slowly start adding in the other controls to make sure it isn't some odd combination or something.

**Comment by bradleygore** [comment]
@arma7x I had some time this weekend and updated to work with updates to android's design lib that took place and caused this issue. Please update to v0.1.4 ( 7992c5b ) and let me know if problems persist.

Thank you,
Bradley
