### ISSUE TITLE
Unable to build project for iOS with this plugin and Xcode 9

### ISSUE THREAD

**Issue by yalva** [bradleygore/nativescript-textinputlayout#30]
I'm facing this error when I'm build for iOS

The target “SkyFloatingLabelTextField” contains source code developed with Swift 2.x. Xcode 9 does not support building or migrating Swift 2.x targets.

Use Xcode 8.x to migrate the code to Swift 3.

**Comment by bradleygore** [comment]
@yalva - make sure you're installing the pod that targets Swift 3+. I've also just updated the plugin so that it has some Podfile info included showing this Pod to install. Please try and see if the updates help your situation.

**Comment by mhmo91** [comment]
@bradleygore Hey man, i would like to thank u for your work, i really appreciate it but u have to rebuild your plugin with swift3, it was a pain in the neck as i had to trace plugin by plugin to know which one was causing this issue... thanks for understanding, wish u the best

**Comment by bradleygore** [comment]
@mhmo91 - appreciate the kind words, but this plugin wasn't built with swift. The Podfile dictates which version of the SkyFloatingLabelTextField cocoa pod you pull in. I've updated the [Podfile that ships with my plugin](https://github.com/bradleygore/nativescript-textinputlayout/blob/master/src/platforms/ios/Podfile) to point to the latest of that cocoa pod, which is built on swift 3, but at the end of the day my understanding (which is admittedly limited in the iOS arena) is that you control all that with your Podfile and not my plugin - i.e. you can override the stuff in the Podfile my plugin ships with..  

cc: @bradmartin - you have any thoughts on this Brad?
