### ISSUE TITLE
Better example on how to style on Android

### ISSUE THREAD

**Issue by MisterBrownRSA** [bradleygore/nativescript-textinputlayout#31]
Hello,

I have commented on #26 and thought it would be best to create a separate issue instead.

I would like to request a more in-depth example which explains where a person should be searching for the proposed styles (XML) changes, and how to apply them.

If someone has an example, that could be used as well.

Thank you for this wonderful plugin

**Comment by bradleygore** [comment]
Hi @MisterBrownRSA 

Please see the example `styles.xml` file in the included demo app: https://github.com/bradleygore/nativescript-textinputlayout/blob/master/demo/app/App_Resources/Android/values/styles.xml

For more in-depth documentation on what TextInputLayout pieces can be styled, and how to style them, please see the [styling docs](https://materialdoc.com/components/text-fields/#how-to-style_1):
