### ISSUE TITLE
Plugin not compatible with NativeScript 3.x.x 

### ISSUE THREAD

**Issue by NickIliev** [bradleygore/nativescript-textinputlayout#6]
NativeScript 3.0.0 has introduced a number of [breaking changes](https://github.com/NativeScript/NativeScript/blob/master/Modules30Changes.md).

Currently, the plugin is throwing with the following when used with nativeScript 3.x.x project.
```
TypeError: Could not load view for: TextInputLayout.Error: com.tns.NativeScriptException: Failed to find module: "ui/core/proxy", rel
ative to: app/tns_modules/
```

Due to changes to the way the property sytem works, the plugin will need to be re-written in the parts where `dependency-observable` properties and `ui/core/proxy` is used

**Comment by cagatayoncul** [comment]
same problem!

**Comment by bradleygore** [comment]
I've not been working on any NativeScript-related projects for the last several months, and have had extremely limited time. Welcome any PRs that get sent my way 😄

**Comment by bradleygore** [comment]
@NickIliev @cagatayoncul 

Check out the `2.0.0` version of this plugin - it is now good to go for NativeScript 3.0!
